######## patient login
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "username": "patient1",
    "password": "patient12345"
}

######## Insurance login
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "username": "insurance1",
    "password": "insurance12345"
}

####### Doctor login
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "username": "doctor1",
    "password": "doctor12345"
}

####### Pharmacy login
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "username": "pharmacy1",
    "password": "pharmacy12345"
}

###### Get homepage patient
get http://localhost:3000/homePage HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhdGllbnQxIiwiaWF0IjoxNzE5MTgwMzM1LCJleHAiOjE3MTkxODAzOTV9.b-rVy169gNxyBlWSSSpFtOxoUmytXiHhFrltQn-WuBE
Content-Type: application/json

###### Get homepage insurance
get http://localhost:3000/homePage HTTP/1.1
Authorization: Bearer
Content-Type: application/json

###### Get homepage doctor
get http://localhost:3000/homePage HTTP/1.1
Authorization: Bearer
Content-Type: application/json

###### Get homepage pharmacy
get http://localhost:3000/homePage HTTP/1.1
Authorization: Bearer
Content-Type: application/json

####### Get prescription insurance
GET http://localhost:3000/prescription HTTP/1.1
Authorization: Bearer
Content-Type: application/json

{
    "patientUsername": "patient1",
    "prescriptionId": "pres1"
}

####### Get prescription doctor
GET http://localhost:3000/prescription HTTP/1.1
Authorization: Bearer
Content-Type: application/json

{
    "patientUsername": "patient1",
    "prescriptionId": "pres1"
}

####### Get prescription patient
GET http://localhost:3000/prescription HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhdGllbnQxIiwiaWF0IjoxNzE5MTgwODY0LCJleHAiOjE3MTkxODA5MjR9.VYmfyVaKlwui6t097VnBHHROEHzdLeBmPhat8SeTiRY
Content-Type: application/json

{
    "prescriptionId": "pres1"
}

####### Get prescription pharmacy
GET http://localhost:3000/prescription HTTP/1.1
Authorization: Bearer
Content-Type: application/json

{
    "patientUsername": "patient1",
    "prescriptionId": "pres1"
}

####### Get patient doctor
GET http://localhost:3000/searchPatient HTTP/1.1
Authorization: Bearer
Content-Type: application/json

{
    "patientId": "patient1"
}

####### Get patient pharmacy
GET http://localhost:3000/searchPatient HTTP/1.1
Authorization: Bearer
Content-Type: application/json

{
    "patientId": "patient1"
}

####### Get patient insurance
GET http://localhost:3000/searchPatient HTTP/1.1
Authorization: Bearer
Content-Type: application/json

{
    "patientId": "patient1"
}

####### Confirm presccription pharmacy error (insurance cannot confirm)
POST http://localhost:3000/confirmPrescriptionPharmacy HTTP/1.1
Authorization: Bearer
Content-Type: application/json

{
    "patientId": "patient1",
    "prescriptionId": "pres1"
}

####### Confirm presccription pharmacy error (pres already purchased)
POST http://localhost:3000/confirmPrescriptionPharmacy HTTP/1.1
Authorization: Bearer
Content-Type: application/json

{
    "patientId": "patient1",
    "prescriptionId": "pres1"
}

####### Confirm presccription pharmacy success
POST http://localhost:3000/confirmPrescriptionPharmacy HTTP/1.1
Authorization: Bearer
Content-Type: application/json

{
    "patientId": "patient1",
    "prescriptionId": "pres3"
}

####### Confirm presccription patient error (username is not a patient)
POST http://localhost:3000/confirmPrescriptionPatient HTTP/1.1
Authorization: Bearer
Content-Type: application/json

{
    "prescriptionId": "pres3"
}

####### Confirm presccription patient error (pres already purchased)
POST http://localhost:3000/confirmPrescriptionPatient HTTP/1.1
Authorization: Bearer
Content-Type: application/json

{
    "pharmacyId": "patient1",
    "prescriptionId": "pres1"
}

####### Confirm presccription patient success
POST http://localhost:3000/confirmPrescriptionPatient HTTP/1.1
Authorization: Bearer
Content-Type: application/json

{
    "pharmacyId": "pharmacy1",
    "prescriptionId": "pres3"
}

####### Write prescription error (Not a doctor)
POST http://localhost:3000/writePrescription HTTP/1.1
Authorization: Bearer
Content-Type: application/json

{
    "patientId": "patient1",
    "prescription": {
        "report": "The patient has severe flu",
        "medicine": [
            {"name": "Aspirin", "dosage": 2, "frequency": 2},
            {"name": "Ibuprofen", "dosage": 2, "frequency": 2},
            {"name": "Acetaminophen", "dosage": 2, "frequency": 2}
        ]
    }
}


###### Write prescription error (Patient does not exist)
POST http://localhost:3000/writePrescription HTTP/1.1
Authorization: Bearer
Content-Type: application/json

{
    "patientId": "patient10",
    "prescription": {
        "report": "The patient has severe flu",
        "medicine": [
            {"name": "Aspirin", "dosage": 2, "frequency": 2},
            {"name": "Ibuprofen", "dosage": 2, "frequency": 2},
            {"name": "Acetaminophen", "dosage": 2, "frequency": 2}
        ]
    }
}


###### Write prescription error (Medicine not stored in the list)
POST http://localhost:3000/writePrescription HTTP/1.1
Authorization: Bearer
Content-Type: application/json

{
    "patientId": "patient1",
    "prescription": {
        "report": "The patient has severe flu",
        "medicine": [
            {"name": "Aspirin", "dosage": 2, "frequency": 2},
            {"name": "Ibuprofen", "dosage": 2, "frequency": 2},
            {"name": "something", "dosage": 2, "frequency": 2}
        ]
    }
}


##### Write prescrition successfully
POST http://localhost:3000/writePrescription HTTP/1.1
Authorization: Bearer
Content-Type: application/json

{
    "patientId": "patient1",
    "prescription": {
        "report": "The patient has severe flu",
        "medicine": [
            {"name": "Aspirin", "dosage": 2, "frequency": 2},
            {"name": "Ibuprofen", "dosage": 2, "frequency": 2},
            {"name": "Acetaminophen", "dosage": 2, "frequency": 2}
        ]
    }
}
