######## patient login
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "username": "patient1",
    "password": "patient12345"
}

######## Insurance login
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "username": "insurance1",
    "password": "insurance12345"
}

####### Doctor login
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "username": "doctor1",
    "password": "doctor12345"
}

####### Pharmacy login
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "username": "pharmacy1",
    "password": "pharmacy12345"
}

###### Get homepage patient
get http://localhost:3000/homePage HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhdGllbnQxIiwiaWF0IjoxNzE5NjA3OTgxLCJleHAiOjE3MTk2MDk3ODF9.jO4dftM4uUIsBfcxPerx9EP4n1OslnybIIgGDFHlQp4
Content-Type: application/json

###### Get homepage insurance
get http://localhost:3000/homePage HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imluc3VyYW5jZTEiLCJpYXQiOjE3MTk2MDc5OTgsImV4cCI6MTcxOTYwOTc5OH0.57sJiqvchDJwDnIgbOCO3mSbC6wI5LCWjblaE-wnq2g
Content-Type: application/json

###### Get homepage doctor
get http://localhost:3000/homePage HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRvY3RvcjEiLCJpYXQiOjE3MTk2MDgwMjEsImV4cCI6MTcxOTYwOTgyMX0.a_QMVANswfxeh8nU-iTL_UPNxVZ_p5I1dvz-f7VoBWA
Content-Type: application/json

###### Get homepage pharmacy
get http://localhost:3000/homePage HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBoYXJtYWN5MSIsImlhdCI6MTcxOTYwODAzNCwiZXhwIjoxNzE5NjA5ODM0fQ.GGQGRLs-FNTZ4YUG5P_qa9mcCN7d8IfG8I_e61y60Dk
Content-Type: application/json

####### Get prescription insurance
POST http://localhost:3000/prescription HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imluc3VyYW5jZTEiLCJpYXQiOjE3MTk2MDc5OTgsImV4cCI6MTcxOTYwOTc5OH0.57sJiqvchDJwDnIgbOCO3mSbC6wI5LCWjblaE-wnq2g
Content-Type: application/json

{
    "patientUsername": "patient1",
    "prescriptionId": "pres1"
}

####### Get prescription doctor
POST http://localhost:3000/prescription HTTP/1.1
Authorization: Bearer .eyJ1c2VybmFtZSI6ImRvY3RvcjEiLCJpYXQiOjE3MTk2MDgwMjEsImV4cCI6MTcxOTYwOTgyMX0.a_QMVANswfxeh8nU-iTL_UPNxVZ_p5I1dvz-f7VoBWA
Content-Type: application/json

{
    "patientUsername": "patient1",
    "prescriptionId": "pres1"
}

####### Get prescription patient
POST http://localhost:3000/prescription HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhdGllbnQxIiwiaWF0IjoxNzE5NjA3OTgxLCJleHAiOjE3MTk2MDk3ODF9.jO4dftM4uUIsBfcxPerx9EP4n1OslnybIIgGDFHlQp4
Content-Type: application/json

{
    "prescriptionId": "pres1"
}

####### Get prescription pharmacy
POST http://localhost:3000/prescription HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBoYXJtYWN5MSIsImlhdCI6MTcxOTYwODAzNCwiZXhwIjoxNzE5NjA5ODM0fQ.GGQGRLs-FNTZ4YUG5P_qa9mcCN7d8IfG8I_e61y60Dk
Content-Type: application/json

{
    "patientUsername": "patient1",
    "prescriptionId": "pres1"
}

####### Get patient doctor
GET http://localhost:3000/searchPatient?patientId=patient1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRvY3RvcjEiLCJpYXQiOjE3MTk2MTAwOTQsImV4cCI6MTcxOTYxMTg5NH0.441RqNUKr-C7gUtdduETJJbW1_TSVYGJAppC9fBhOy0
Content-Type: application/json

{
    "patientId": "patient1"
}

####### Get patient pharmacy
GET http://localhost:3000/searchPatient?patientId=patient1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBoYXJtYWN5MSIsImlhdCI6MTcxOTYxMDExMiwiZXhwIjoxNzE5NjExOTEyfQ.BThwVVUyOo_aGOKXm4KR1l3a29ETV_RdwpG0ixzOMIA
Content-Type: application/json

{
    "patientId": "patient1"
}

####### Get patient insurance
GET http://localhost:3000/searchPatient?patientId=patient1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imluc3VyYW5jZTEiLCJpYXQiOjE3MTk0NDQ2NTMsImV4cCI6MTcxOTQ0NjQ1M30.GT0JHoccidR_DF_sJTu3DyHvpCjZs_F5uzKAMRaWTc0
Content-Type: application/json

{
    "patientId": "patient1"
}

###### Insurance Claims Page
GET http://localhost:3000/insuranceClaims HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imluc3VyYW5jZTEiLCJpYXQiOjE3MTk2MTAwNzcsImV4cCI6MTcxOTYxMTg3N30.sfrYl8Uly9wgDD6U22RryFxOHM0OGcqUQkjh25VYCYU
Content-Type: application/json

{
    "patientId": "patient1"
}

####### Confirm presccription pharmacy error (insurance cannot confirm)
POST http://localhost:3000/confirmPrescriptionPharmacy HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imluc3VyYW5jZTEiLCJpYXQiOjE3MTk2MTAwNzcsImV4cCI6MTcxOTYxMTg3N30.sfrYl8Uly9wgDD6U22RryFxOHM0OGcqUQkjh25VYCYU
Content-Type: application/json

{
    "patientId": "patient1",
    "prescriptionId": "pres1"
}

####### Confirm presccription pharmacy error (pres already purchased)
POST http://localhost:3000/confirmPrescriptionPharmacy HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBoYXJtYWN5MSIsImlhdCI6MTcxOTYxMDExMiwiZXhwIjoxNzE5NjExOTEyfQ.BThwVVUyOo_aGOKXm4KR1l3a29ETV_RdwpG0ixzOMIA
Content-Type: application/json

{
    "patientId": "patient1",
    "prescriptionId": "pres1"
}

####### Confirm presccription pharmacy success
POST http://localhost:3000/confirmPrescriptionPharmacy HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBoYXJtYWN5MSIsImlhdCI6MTcxOTYxMjA0MSwiZXhwIjoxNzE5NjEzODQxfQ.l-_Rdx0E-Y2w0VGzeDSD9NwSDpRjpwUoyXt_zIjJJ6c
Content-Type: application/json

{
    "patientId": "patient1",
    "prescriptionId": "pres4"
}

####### Confirm presccription patient error (pres already purchased)
POST http://localhost:3000/confirmPrescriptionPatient HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhdGllbnQxIiwiaWF0IjoxNzE5NjEyMDU4LCJleHAiOjE3MTk2MTM4NTh9.dFxRDrC27fhdysAMGVDfVaivGHk8KErMpmYvWBPaOlg
Content-Type: application/json

{
    "pharmacyId": "patient1",
    "prescriptionId": "pres1"
}

####### Confirm presccription patient success
POST http://localhost:3000/confirmPrescriptionPatient HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhdGllbnQxIiwiaWF0IjoxNzE5NjEyMDU4LCJleHAiOjE3MTk2MTM4NTh9.dFxRDrC27fhdysAMGVDfVaivGHk8KErMpmYvWBPaOlg
Content-Type: application/json

{
    "pharmacyId": "pharmacy1",
    "prescriptionId": "pres4"
}

####### Write prescription error (Not a doctor)
POST http://localhost:3000/writePrescription HTTP/1.1
Authorization: Bearer 
Content-Type: application/json

{
    "patientId": "patient1",
    "prescription": {
        "report": "The patient has severe flu",
        "medicine": [
            {"name": "Aspirin", "dosage": 2, "frequency": 2},
            {"name": "Ibuprofen", "dosage": 2, "frequency": 2},
            {"name": "Acetaminophen", "dosage": 2, "frequency": 2}
        ]
    }
}


###### Write prescription error (Patient does not exist)
POST http://localhost:3000/writePrescription HTTP/1.1
Authorization: Bearer
Content-Type: application/json

{
    "patientId": "patient10",
    "prescription": {
        "report": "The patient has severe flu",
        "medicine": [
            {"name": "Aspirin", "dosage": 2, "frequency": 2},
            {"name": "Ibuprofen", "dosage": 2, "frequency": 2},
            {"name": "Acetaminophen", "dosage": 2, "frequency": 2}
        ]
    }
}


###### Write prescription error (Medicine not stored in the list)
POST http://localhost:3000/writePrescription HTTP/1.1
Authorization: Bearer
Content-Type: application/json

{
    "patientId": "patient1",
    "prescription": {
        "report": "The patient has severe flu",
        "medicine": [
            {"name": "Aspirin", "dosage": 2, "frequency": 2},
            {"name": "Ibuprofen", "dosage": 2, "frequency": 2},
            {"name": "something", "dosage": 2, "frequency": 2}
        ]
    }
}


##### Write prescrition successfully
POST http://localhost:3000/writePrescription HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRvY3RvcjEiLCJpYXQiOjE3MTk2MTIwNzIsImV4cCI6MTcxOTYxMzg3Mn0.M0Qkwm_sj1wdt__jMwF4BC05FPZb3j3hRIaLfIyKANA
Content-Type: application/json

{
    "patientId": "patient1",
    "prescription": {
        "report": "The patient has severe flu",
        "medicine": [
            {"name": "Aspirin", "dosage": 2, "frequency": 2},
            {"name": "Ibuprofen", "dosage": 2, "frequency": 2},
            {"name": "Acetaminophen", "dosage": 2, "frequency": 2}
        ]
    }
}


###### Get medicine List
GET http://localhost:3000/medicines HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRvY3RvcjEiLCJpYXQiOjE3MTk2MTQxNjEsImV4cCI6MTcxOTYxNTk2MX0.05zQqUyZ8m-5SN8d9Yc_AXs1CFmRbQ0H3qHbFTmqBN8
Content-Type: application/json
