{
 "title": "Hyperledger Fabric Monitoring",
 "description": "Monitoring dashboard for the HealthChain insurance system",
 "time": { "from": "2024-11-04T11:53:45.230Z", "to": "2024-11-04T23:53:45.230Z" },
 "panels": [
  { "title": "Hyperledger Fabric Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fabric Verison",
   "type": "stat",
   "description": "The working version of Hyperledger Fabric.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (version) (fabric_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ledger Block Height",
   "type": "stat",
   "description": "The number of blocks created on the blockchain.",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (channel) (ledger_blockchain_height{instance=~\"peer.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Count",
   "type": "stat",
   "description": "Valid Transactions on the ledger.",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ledger_transaction_count{channel=\"chainhealth-channel\", chaincode=\"chainHeath-ChainCode:1.0\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Couch DB Processing Time",
   "type": "timeseries",
   "description": "Time taken in seconds for the function to complete request to CouchDB.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(couchdb_processing_time_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}